### ISSUE TITLE
Demo?

### ISSUE THREAD

**Issue by marcosabb** [LajackBR/ProjetosJS#1]
Beleza cara?

Seria bacana tu colocar algum demo/preview dos projetos!

:smile:

**Comment by LajackBR** [comment]
Pow cara ótima ideia. Como sou iniciante, esses projetos serão (inicialmente) coisas simples para me ajudar a fixar o aprendizado em JS. Por agora não sei se vai rolar, pois quero me concentrar no código, mas vou tentar fazer, pelo menos, ao término de cada projeto.

**Comment by marcosabb** [comment]
Ótimo cara! Se precisar de ajuda, tamo ae. :)
